name: pattern_formatter
description: A Flutter package provides some implementations of  TextInputFormatter that format input with pre-defined patterns
version: 0.0.2
author: Hung Duy Ha <hunghd.yb@gmail.com>
homepage: https://github.com/hnvn/flutter_pattern_formatter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: